{
 "title": "RG Node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "CPU / RAM / Disk / SWAP usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "graph",
   "description": "Average CPU usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{mode=\"idle\"}[5m]) * 100)",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "graph",
   "description": "RAM memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)",
     "legendFormat": "RAM memory usage"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "graph",
   "description": "Disk space usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg((1 - node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100)",
     "legendFormat": "Disk space usage"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "graph",
   "description": "SWAP usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / (node_memory_SwapTotal_bytes)) * 100",
     "legendFormat": "SWAP Usage"
    }
   ]
  }
 ]
}