{
 "title": "Rails",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Puma", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Puma overload",
   "type": "graph",
   "description": "percentage showing how busy puma web server loads",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": " (1.0 - sum(puma_pool_capacity) / sum(puma_max_threads)) * 100",
     "legendFormat": "App busy"
    },
    { "legendFormat": "puma_pool_capacity" }
   ]
  },
  {
   "title": "Puma Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(puma_max_threads)", "legendFormat": "max threads" },
    { "expr": "sum(puma_running)", "legendFormat": "running threads" },
    { "expr": "sum(puma_pool_capacity)", "legendFormat": "capacity threads" }
   ]
  },
  { "title": "Rails", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Throughput (reqpm)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_requests_total[1m]))*60",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Rails average response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_request_duration_seconds_sum[1m]))\n/\nsum(rate(rails_request_duration_seconds_count[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(rails_db_runtime_seconds_sum[1m]))\n/\nsum(rate(rails_db_runtime_seconds_count[1m]))",
     "legendFormat": "ActiveRecord"
    },
    {
     "expr": "sum(rate(rails_view_runtime_seconds_sum[1m]))\n/\nsum(rate(rails_view_runtime_seconds_count[1m]))",
     "legendFormat": "Views"
    }
   ]
  },
  {
   "title": "Rails throughput per endpoint (reqpm)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_requests_total[1m])) by (controller, action) * 60",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Rails 95% response time by endpoint",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rails_request_duration_seconds_bucket[1m])) by (le,controller,action)) * 1000 ",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  { "title": "Sidekiq", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Total jobs processed (ps)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_success_total[1m]))",
     "legendFormat": "Total processed jobs"
    },
    {
     "expr": "sum(rate(sidekiq_jobs_failed_total[1m]))",
     "legendFormat": "Failed jobs"
    }
   ]
  },
  {
   "title": "Sidekiq Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Waiting jobs count" }
   ],
   "targets": [
    {
     "expr": "max(sidekiq_jobs_waiting_count) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Job processing time 95 percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(sidekiq_job_runtime_seconds_bucket[1m])) by (le)) ",
     "legendFormat": "95% quantile of sidekiq "
    }
   ]
  },
  {
   "title": "Job processing time 95% by job type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(sidekiq_job_runtime_seconds_bucket[1m])) by (worker, le)) ",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Sidekiq jobs pushed by queue (ps)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(sidekiq_jobs_enqueued_total[1m])) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Sidekiq Retry Set by queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sidekiq_jobs_retry_count) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Sidekiq jobs processed by queue (ps)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(sidekiq_jobs_success_total[1m])) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Sidekiq jobs processed by job type (ps)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(sidekiq_jobs_success_total[1m])) by (worker)",
     "legendFormat": "{{worker}}"
    }
   ]
  }
 ]
}