  prometheus:
    image: prom/prometheus:v2.12.0
    ports:
      - '9090:9090'
    volumes:
      - ./.prometheus:/etc/prometheus
    depends_on:
      - rails
    command:
      - --config.file=/etc/prometheus/config.yml

  grafana:
    image: grafana/grafana:6.3.5
    depends_on:
      - prometheus
    ports:
      - '5000:3000'
    volumes:
      - ./.grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./.grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./.grafana/provisioning/notifiers:/etc/grafana/provisioning/notifiers
      - ./.grafana/dashboards:/var/lib/grafana/dashboards

  node_exporter:
    image: prom/node-exporter:v0.18.1
    ports:
      - '9100:9100'
